mensaje.application=Aplicacion Web con Spring, scgr
spring.application.name=${APP_NAME:scgr}

#server.port=8080

logging.level.org.springframework.security=DEBUG

#configuracion thymeleaf
spring.thymeleaf.prefix=classpath:/paginas/
spring.thymeleaf.suffix=.html

#Datasource MariaDB
#spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mariadb://localhost:3306/scgr?useSSL=false&serverTimezone=UTC
spring.datasource.username=pixupdb_owner
spring.datasource.password=pixupdb_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#Mas configuraciones de MariaDB
#create,none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Siempre se inicialice utilizando scripts SQL
#always,never
spring.sql.init.mode=never

# Ejecutar data.sql después de crear las tablas
#spring.jpa.defer-datasource-initialization=true

#ruta de archivos
#ejemplo.imagen.ruta=/home/mash/imagenes/scgr
#spring.servlet.multipart.max-file-size = 5MB
#spring.servlet.multipart.max-request-size = 5MB

#pdf
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.pdf=application/pdf